version: "3"
services:
  reverseproxy:
    build:
      context: ./reverse-proxy
    image: reverseproxy
  backend_user:
    build:
      context: ./user-service
    image: udagram-api-user
  backend_feed:
    build:
      context: ./feed-service
    image: udagram-api-feed
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend
